# Third-party runtime libraries the plug-in may ship, one per line: group:artifact=licence.
# Read by the verifyDependencyLicences task (research R21, SC-006). The build fails on any external
# artifact on the composed modules' runtime classpath that is not listed here with one of
# Apache-2.0, MIT, BSD-2-Clause, BSD-3-Clause or CC0-1.0. The IntelliJ Platform is not counted.
# There are no third-party runtime libraries today, so this list is empty.
